openapi: 3.0.0
info:
  title: BRCAid API
  description: API for the survey flow work
  version: 1.0.0
servers:
  - url: /brcaid/


paths:

  /about:
    get:
      summary: Returns a version info
      description: Optional extended description in Markdown.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AboutResponse'

  /survey/v1/formdata:
    get:
      description: Gets the data for needed by the UI to make the forms
      summary: Gets form data
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SurveyFormdData'
        '400':
          description: something went wrong with the user input processing or internally, see the error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /survey/v1/survey-contacts:
    post:
      summary: Used to post a form from the general public
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SurveyContact'

      responses:
        '201':
          description: Form accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SurveyContactResp'
        '400':
          description: something went wrong with the user input processing or internally, see the error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /brcaid/v1/login:
    post:
      summary: Logs a user in
      description: see summary
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '201':
          description: User logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: User not authorized to login, bad password and/or user id
        '400':
          description: something went wrong with the user input processing or internally, see the error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /brcaid/v1/logout:
    post:
      summary: Logs out the user
      description: Logs the user out using the auth header provided in the call
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'

      responses:
        '204':
          description: no content, logout success


  /brcaid/v1/survey-contacts:
    get:
      security:
        - AuthHeaderToken: []
      summary: Gets a list of users
      description: gets list surveys.  Results from this call have PII empty
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SurveyContact'

  /brcaid/v1/users:
    get:
      security:
        - AuthHeaderToken: []
      summary: Gets a list of users
      description: gets list of users
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Adds a new user
      description: adds a new user, leave the user uuid blank, its not needed here, server fills it in
      security:
        - AuthHeaderToken: []
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User add
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Something was wrong with the user input or on the server, see the response for details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'



components:
  securitySchemes:
    AuthHeaderToken:
      type: apiKey
      name: Authorization
      in: header

  parameters:
    AuthorizationHeader:
      name: Authorization
      in: header
      description: The authorization token
      schema:
        type: string
      required: true

  schemas:
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          description: An I18N string
          type: string
        parameters:
          type: object
          additionalProperties:
            type: string

    AboutResponse:
      type: object
      properties:
        appVersion:
          type: string
        apiVersions:
          type: array
          items:
            type: string


    SurveyFormdData:
      type: object
      properties:
        skiils:
          type: array
          items:
            $ref: '#/components/schemas/Skill'

    Skill:
      type: object
      properties:
        skillID:
          type: string
        skillText:
          type: string
    User:
      type: object
      properties:
        userUUID:
          type: string
          description: Non mutable internal identifier for the user.  Set by the server, not needed as input for adding a user
          readOnly: true
        userID:
          description: user supplied ID (Can be anything including an email)
          type: string
        password:
          description: Password, need for adding a user, never filled in otherwise
          type: string
          writeOnly: true
        email:
          type: string
          description: the email
        phone:
          type: string
          description: phone

    Group:
      type: object
      properties:
        groupUUID:
          type: string
          description: Internal ID for the group, generated by the server, never supplied by the user
          readOnly: true
        name:
          type: string
        description:
          type: string

    Login:
      type: object
      properties:
        userID:
          type: string
          description: The user supplied user ID
        password:
          type: string
          description: password for the user
      required:
        - userID
        - password


    LoginResponse:
      type: object
      properties:
        autoToken:
          type: string
          description: auto token to pass in the auth header (todo, document the auth header)


    SurveyContactPII:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        preferedContact:
          type: string
          description: an enum really, phone or email

    SurveyContactResp:
      type: object
      properties:
        requestUUID:
          type: string

    SurveyContact:
      type: object
      properties:
        requestingHelp:
          type: boolean
        offeringHelp:
          type: boolean
        needHelpNow:
          type: boolean
        offeredSkills:
          type: array
          items:
            type: string
        neededSkills:
          type: array
          items:
            type: string
        zip:
          type: string
          description: 5 digit zip code

        conactInfo:
          $ref: '#/components/schemas/SurveyContactPII'
